import { ENVIRONMENT_OBJECTS, FLOWER_NAMES, ROCK_NAMES, TERRAIN_TILES, WEED_NAMES } from '../../base/enums';

export const mapData = [
  [
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
     { terrainType: "", enviromentObject: '' },
    { terrainType: "", enviromentObject: '' },
    { terrainType: "", enviromentObject: '' },

  ],
  [
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },

    { terrainType: '', enviromentObject: '' },
  ],
  [
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject:  WEED_NAMES.WEED_1  },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject:""},
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
  [
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_1 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_1 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
  ],
  [
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_1 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
  ],
  [
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: WEED_NAMES.WEED_1 },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
  ],
  [
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: WEED_NAMES.WEED_1 },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_1 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
  ],
  [
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_1 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
  ],
  [
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: WEED_NAMES.WEED_1 },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
  [
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
  //** */
  [
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
  [
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_1 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
  [
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: WEED_NAMES.WEED_1 },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.HILL, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_1 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_1 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.FARMLAND, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.FARMLAND, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.FARMLAND, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.FARMLAND, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: ENVIRONMENT_OBJECTS.TREE },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: WEED_NAMES.WEED_1 },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: TERRAIN_TILES.GRASS, enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
];
