import { FLOWER_NAMES, ROCK_NAMES, WEED_NAMES } from '../../base/enums';

export const mapData = [
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: 'tree' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: 'tree' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: 'tree' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
  ],
  [
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
  ],
  [
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: 'tree' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: 'tree' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject:  "" },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject:"" },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: 'tree' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: 'tree' },
    { terrainType: 'grass', enviromentObject: ''  },
    { terrainType: 'grass', enviromentObject:      "" },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
  ],
  [
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: ""},
    { terrainType: 'grass', enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: WEED_NAMES.WEED_1 },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: 'tree' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
  ],
  [
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: WEED_NAMES.WEED_2 },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: 'tree' },
    { terrainType: 'grass', enviromentObject: '' },
  ],
  [
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject:     ""},
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
  ],
  [
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject:     WEED_NAMES.WEED_2},
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: ROCK_NAMES.STONE_1 },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject:   WEED_NAMES.WEED_1},
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
  [
    { terrainType: '', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: 'grass', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
    { terrainType: '', enviromentObject: '' },
  ],
];
