export const mapData = [
    { id: '1', x: 0, y: 0, type: 'grass' },
    { id: '2', x: 1, y: 0, type: 'water' },
    { id: '3', x: 2, y: 0, type: 'grass' },
    { id: '4', x: 3, y: 0, type: 'grass' },
    { id: '5', x: 4, y: 0, type: 'grass' },
    { id: '6', x: 0, y: 1, type: 'grass' },
    { id: '7', x: 1, y: 1, type: 'grass' },
    { id: '8', x: 2, y: 1, type: 'grass' },
    { id: '9', x: 3, y: 1, type: 'grass' },
    { id: '10', x: 4, y: 1, type: 'grass' },
    { id: '11', x: 0, y: 2, type: 'grass' },
    { id: '12', x: 1, y: 2, type: 'grass' },
    { id: '13', x: 2, y: 2, type: 'grass' },
    { id: '14', x: 3, y: 2, type: 'grass' },
    { id: '15', x: 4, y: 2, type: 'grass' },
    { id: '16', x: 0, y: 3, type: 'grass' },
    { id: '17', x: 1, y: 3, type: 'grass' },
    { id: '18', x: 2, y: 3, type: 'grass' },
    { id: '19', x: 3, y: 3, type: 'grass' },
    { id: '20', x: 4, y: 3, type: 'grass' },
    { id: '21', x: 0, y: 4, type: 'grass' },
    { id: '22', x: 1, y: 4, type: 'grass' },
    { id: '23', x: 2, y: 4, type: 'grass' },
    { id: '24', x: 3, y: 4, type: 'grass' },
    { id: '25', x: 4, y: 4, type: 'grass' },
];
