import { AXE_ICON_INVENTORY, HOE_ICON_INVENTORY } from "../assets/items/inventory";
import { TILE_TYPES, TERRAIN_TILES, TOOL_NAMES } from "./enums";

export const TILE_SIZE = 0.9;
export const WALKABLE_TILES = [TILE_TYPES.GRASS, TILE_TYPES.DIRT];
export const VALID_TERRAIN_TILES = [TERRAIN_TILES.WATER, TERRAIN_TILES.DIRT, TERRAIN_TILES.GRASS, TERRAIN_TILES.FARMLAND];

