import { AXE_ICON_INVENTORY, HOE_ICON_INVENTORY } from '../assets/items/inventory';
import { TILE_TYPES, TERRAIN_TILES, TOOL_NAMES, ENVIRONMENT_OBJECTS } from './enums';

export const TILE_SIZE = 0.9;
export const WALKABLE_TILES = [TILE_TYPES.GRASS, TILE_TYPES.DIRT];
export const VALID_TERRAIN_TILES = [TERRAIN_TILES.WATER, TERRAIN_TILES.DIRT, TERRAIN_TILES.GRASS, TERRAIN_TILES.FARMLAND];
export const VALID_ENVITONMENT_OBJECTS_TILES = [ENVIRONMENT_OBJECTS.TREE, ENVIRONMENT_OBJECTS.ROCK, ENVIRONMENT_OBJECTS.BUSH, ENVIRONMENT_OBJECTS.FLOWER, ENVIRONMENT_OBJECTS.WEED];
export const TIME_SPEED = 100;
export const START_TIME = 8;
export const MAX_TREE_FRUIT_GROWTH_STAGE = 4;
export const MAX_CROP_GROWTH_STAGE = 3;
export const INITIAL_CROP_GROWTH_STAGE = 1;
export const INITIAL_FRUIT_GROWTH_STAGE = 1;
export const PLAYER_SPEED = 0.13;
export const PLAYER_START_POSITION = { x: 3, y: 3 };